# Generated by Django 5.0.2 on 2025-05-14 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'signalement', 'verbose_name_plural': 'signalements'},
        ),
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(default=' ', max_length=255, verbose_name='adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('route', 'Route endommagée'), ('electricity', 'Panne électrique'), ('waste', 'Déchets non collectés'), ('other', 'Autre')], max_length=50, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
